base:
  url: <%= ENV.fetch("BASE_URL") { "https://share-station.info" } %>

aws:
  access_key_id: <%= ENV.fetch("AWS_ACCESS_KEY_ID") %>
  secret_access_key: <%= ENV.fetch("AWS_SECRET_ACCESS_KEY") %>
  region: <%= ENV.fetch("AWS_REGION") { "ap-northeast-1" } %>

  image:
    bucket: <%= ENV.fetch("AWS_BUCKET_NAME") %>

image:
  url: <%= ENV.fetch("IMAGE_URL") { "https://img.share-station.info" } %>
